services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/DB_PASSWORD
      MYSQL_USER: root
      MYSQL_DATABASE: shwi_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql/data
    secrets:
      - DB_PASSWORD

  api:
    build: ./api
    restart: always
    env_file:
      - ./api/.env
    environment:
      - MYSQL_HOST=db
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - logs:/app/logs

  ui:
    build: ./ui
    restart: always
    env_file:
      - ./ui/.env
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  mysql_data:
  logs:

secrets:
  DB_PASSWORD:
    file: ./DB_PASSWORD.txt
